'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {proxy}=require('../api/_proxy.cjs');
const env={APPROVED_BACKEND_ORIGIN:'https://backend.example',APPROVED_GATEWAY_KEY:'server-secret'};
function res(){return {statusCode:200,headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},end(v){this.body=v;}};}
async function call(path,req={},fetcher=async()=>new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json'}})){const response=res();await proxy({method:'GET',url:path,headers:{},...req},response,path,env,fetcher);return response;}
test('method and query allowlist reject before contacting backend',async()=>{let calls=0;const fetcher=()=>{calls++;throw Error('must not call');};for(const [path,req,code] of [['/api/run',{},405],['/api/state',{url:'/api/state?x=1'},400],['/',{url:'/?x=1'},400],['/approver/api/tap',{method:'POST',headers:{'content-type':'application/json'}},401]]){const r=await call(path,req,fetcher);assert.equal(r.statusCode,code);}assert.equal(calls,0);});
test('session allocation injects only server credential',async()=>{let observed;const r=await call('/api/session',{method:'POST',url:'/api/session',headers:{'content-type':'application/json',cookie:'evil',authorization:'Bearer evil','x-approved-gateway':'evil'},body:{}},async(url,opts)=>{observed={url,opts};return new Response(JSON.stringify({session_token:'abc'}),{headers:{'content-type':'application/json','set-cookie':'bad=1'}});});assert.equal(r.statusCode,200);assert.equal(observed.url,'https://backend.example/api/session');assert.equal(observed.opts.headers['X-Approved-Gateway'],'server-secret');assert.equal(observed.opts.headers.Cookie,undefined);assert.equal(observed.opts.headers.Authorization,undefined);assert.equal(r.headers['set-cookie'],undefined);assert.match(r.headers['cache-control'],/no-store/);});
test('session token is forwarded to one fixed backend route',async()=>{let observed;const session='a'.repeat(32);const r=await call('/api/state',{headers:{'x-approved-session':session}},async(url,opts)=>{observed={url,opts};return new Response('{}',{headers:{'content-type':'application/json'}});});assert.equal(r.statusCode,200);assert.equal(observed.url,'https://backend.example/api/state');assert.equal(observed.opts.headers['X-Approved-Session'],session);});
test('rejects oversized post and upstream redirects and hides raw errors',async()=>{const session='a'.repeat(32);let r=await call('/approver/api/tap',{method:'POST',headers:{'x-approved-session':session,'content-type':'application/json'},body:{data:'x'.repeat(2000)}},()=>{throw Error('must not call');});assert.equal(r.statusCode,413);r=await call('/health',{},async()=>new Response('',{status:302,headers:{location:'https://attacker.example'}}));assert.equal(r.statusCode,502);assert.equal(r.headers.location,undefined);r=await call('/health',{},async()=>new Response('private stack trace',{status:500}));assert.equal(r.statusCode,502);assert.doesNotMatch(r.body,/private stack trace/);});
test('invalid configured origins fail closed',()=>{const {originFromEnv}=require('../api/_proxy.cjs');for(const value of ['http://localhost:3000','https://user:pass@host.example','https://host.example/path','https://host.example?q=1'])assert.throws(()=>originFromEnv({APPROVED_BACKEND_ORIGIN:value}));});

test('configured Maritime base path is fixed',async()=>{const base={...env,APPROVED_BACKEND_ORIGIN:'https://api.maritime.sh/a/12345678-1234-1234-1234-123456789abc/'};let target;const r=res();await proxy({method:'GET',url:'/health',headers:{}},r,'/health',base,async(url)=>{target=url;return new Response('{}',{headers:{'content-type':'application/json'}});});assert.equal(r.statusCode,200);assert.equal(target,'https://api.maritime.sh/a/12345678-1234-1234-1234-123456789abc/health');});

test('response stream is capped before buffering all data',async()=>{const r=res();await proxy({method:'GET',url:'/health',headers:{}},r,'/health',env,async()=>new Response(new Uint8Array(1024*1024+1),{headers:{'content-type':'application/json'}}));assert.equal(r.statusCode,502);assert.doesNotMatch(r.body,/secret/);});
test('timeout covers a stalled response body',async()=>{const r=res();await proxy({method:'GET',url:'/health',headers:{}},r,'/health',env,async(_url,opts)=>new Response(new ReadableStream({start(controller){opts.signal.addEventListener('abort',()=>controller.error(Error('aborted')));}}),{headers:{'content-type':'application/json'}}),20);assert.equal(r.statusCode,502);});
test('page CSP pins fixed inline code by hash',async()=>{const r=res();await proxy({method:'GET',url:'/',headers:{}},r,'/',env,async()=>new Response('<html><style>body{color:red}</style><script>window.ok=1</script></html>',{headers:{'content-type':'text/html'}}));assert.equal(r.statusCode,200);assert.match(r.headers['content-security-policy'],/script-src 'sha256-/);assert.match(r.headers['content-security-policy'],/style-src 'sha256-/);assert.doesNotMatch(r.headers['content-security-policy'],/unsafe-inline/);});
test('gateway shell renders without contacting a sleeping backend',async()=>{const r=res();await proxy({method:'GET',url:'/?auto=1',headers:{}},r,'/',{},async()=>{throw Error('backend asleep');});assert.equal(r.statusCode,200);assert.match(String(r.body),/Get Approved/);assert.match(r.headers['content-security-policy'],/script-src 'sha256-/);});

test('budget refusal is explicit without passing backend details through',async()=>{const r=await call('/api/run',{method:'POST',headers:{'content-type':'application/json','x-approved-session':'a'.repeat(32)},body:{}},async()=>new Response(JSON.stringify({code:'budget-exhausted',message:'private ledger path and token'}),{status:503,headers:{'content-type':'application/json'}}));assert.equal(r.statusCode,503);assert.match(r.body,/allowance is used up/);assert.match(r.body,/approval buttons still work/);assert.doesNotMatch(r.body,/private ledger/);});
