#!/usr/bin/env bash
# Build (or advance) the local branch Maritime deploys the try-it image from.
#
# Maritime's GitHub route builds only a file named exactly `Dockerfile` at the repository root,
# and on main that file is the judge image. This script makes one commit on a separate branch
# (default `deploy/tryit`) whose tree is a committed source revision (default HEAD) with two
# files swapped in at the root:
#
#   Dockerfile     <- images/tryit/Dockerfile            (byte for byte)
#   .dockerignore  <- images/tryit/Dockerfile.dockerignore
#
# It uses git plumbing on a temporary index: the working tree, the real index and the
# current branch are never touched. The new commit's parent is the branch's previous tip when
# there is one, so pushing it is always a fast-forward. It NEVER pushes; it prints the command.
#
#   scripts/tryit-deploy-branch.sh [source-rev] [branch]
set -euo pipefail

source_rev="${1:-HEAD}"
branch="${2:-deploy/tryit}"
root="$(git rev-parse --show-toplevel)"
cd "$root"

source_sha="$(git rev-parse --verify "${source_rev}^{commit}")"
dockerfile="$(git rev-parse --verify "${source_sha}:images/tryit/Dockerfile")"
ignore="$(git rev-parse --verify "${source_sha}:images/tryit/Dockerfile.dockerignore")"

index="$(mktemp "${TMPDIR:-/tmp}/tryit-index.XXXXXX")"
trap 'rm -f "$index"' EXIT
GIT_INDEX_FILE="$index" git read-tree "$source_sha"
GIT_INDEX_FILE="$index" git update-index --cacheinfo "100644,${dockerfile},Dockerfile"
GIT_INDEX_FILE="$index" git update-index --cacheinfo "100644,${ignore},.dockerignore"
tree="$(GIT_INDEX_FILE="$index" git write-tree)"

parents=()
if previous="$(git rev-parse --verify --quiet "refs/heads/${branch}")"; then
  if [ "$(git rev-parse "${previous}^{tree}")" = "$tree" ]; then
    echo "tryit-deploy-branch: ${branch} already carries ${source_sha:0:12}; nothing to do"
    exit 0
  fi
  parents=(-p "$previous")
fi
parents+=(-p "$source_sha")

message="deploy(tryit): root Dockerfile is images/tryit/Dockerfile at ${source_sha:0:12}

Generated by scripts/tryit-deploy-branch.sh for Maritime's GitHub route, which builds only
the root Dockerfile. Do not edit this branch by hand; regenerate it from main."
commit="$(git commit-tree "$tree" "${parents[@]}" -m "$message")"
git update-ref "refs/heads/${branch}" "$commit"
echo "tryit-deploy-branch: ${branch} -> ${commit:0:12} (source ${source_sha:0:12})"
echo "push it (a human step): git push origin ${branch}"
